export const SESSION_AUTO_LOGOUT = "SESSION_AUTO_LOGOUT";
export const SESSION_AUTH_USER = "SESSION_AUTH_USER";
export const SESSION_AUTH_START = "SESSION_AUTH_START";
export const SESSION_AUTH_SUCCESS = "SESSION_AUTH_SUCCESS";
export const SESSION_AUTH_FAIL = "SESSION_AUTH_FAIL";
export const SESSION_ATTEMPT_AUTO_LOGIN = "SESSION_ATTEMPT_AUTO_LOGIN";
export const SESSION_INITIATE_LOGOUT = "SESSION_INITIATE_LOGOUT";
export const SESSION_LOGOUT = "SESSION_LOGOUT";
export const SESSION_UPDATE = "SESSION_UPDATE";
export const SESSION_UPDATE_START = "SESSION_UPDATE_START";
export const SESSION_UPDATE_SUCCESS = "SESSION_UPDATE_SUCCESS";
export const SESSION_UPDATE_FAILED = "SESSION_UPDATE_FAILED";

export const BOTTLES_GET_ALL = "BOTTLES_GET_ALL";
export const BOTTLES_GET_ALL_START = "BOTTLES_GET_ALL_START";
export const BOTTLES_GET_ALL_SUCCESS = "BOTTLES_GET_ALL_SUCCESS";
export const BOTTLES_GET_ALL_FAILED = "BOTTLES_GET_ALL_FAILED";

export const BOTTLE_CREATE_INIT = "BOTTLE_CREATE_INIT";
export const BOTTLE_CREATE = "BOTTLE_CREATE";
export const BOTTLE_EDIT = "BOTTLE_EDIT";
export const BOTTLE_EDIT_SUCCESS = "BOTTLE_EDIT_SUCCESS";
export const BOTTLE_CREATION_START = "BOTTLE_CREATION_START";
export const BOTTLE_CREATION_SUCCESS = "BOTTLE_CREATION_SUCCESS";
export const BOTTLE_CREATION_FAILED = "BOTTLE_CREATION_FAILED";

export const INVESTORS_GET = "INVESTORS_GET";
export const INVESTORS_GET_START = "INVESTORS_GET_START";
export const INVESTORS_GET_SUCCESS = "INVESTORS_GET_SUCCESS";
export const INVESTORS_GET_FAILED = "INVESTORS_GET_FAILED";

export const INVENTORY_LOAD = "INVENTORY_LOAD";
export const INVENTORY_LOAD_START ="INVENTORY_LOAD_START";
export const INVENTORY_LOAD_SUCCESS = "INVENTORY_LOAD_SUCCESS";
export const INVENTORY_LOAD_FAILED = "INVENTORY_LOAD_FAILED";
export const INVENTORY_CREATE_INIT = "INVENTORY_CREATE_INIT";
export const INVENTORY_CREATE = "INVENTORY_CREATE";
export const INVENTORY_CREATION_START = "INVENTORY_CREATION_START";
export const INVENTORY_CREATION_SUCCESS = "INVENTORY_CREATION_SUCCESS";
export const INVENTORY_CREATION_FAILED = "INVENTORY_CREATION_FAILED";